version: '3'
services:
  redis:
    image: "redis:alpine"
    networks: 
      - backend
  server:
    build: .
    environment:
      - PAGE_ACCESS_TOKEN=EAAghoEKyd5cBAGderxFSyBm96pUU2iGNC4tbAMw8s1iVYRaiIwedtfq5ZArvGZBS5hpAnEGavOzhlA33fTTFm0ysE5OTKDqeuklAlzsPa6Y6FFCZC4QEkqjxNZBcjdqm17DGywGjD2ojuff36zh4dn5skAWLoXNfDWvFtWc44SFSoUWn0VUJ
      - VERIFY_TOKEN=echo
    volumes:
      - .:/go/src/chatbot
    links:
      - redis
    ports:
      - "80:8080"
    networks: 
      - backend
    depends_on:
      - redis
    entrypoint: CompileDaemon -log-prefix=false -build="go build -o chatbot" -command="./chatbot"
networks:
  backend:
